//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QA_Helper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QA_Helper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1 {
            get {
                object obj = ResourceManager.GetObject("1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1435857538_icon_81_document_add {
            get {
                object obj = ResourceManager.GetObject("1435857538_icon-81-document-add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1435861088_plus_sign {
            get {
                object obj = ResourceManager.GetObject("1435861088_plus-sign", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1435861114_edit {
            get {
                object obj = ResourceManager.GetObject("1435861114_edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1435861155_edit {
            get {
                object obj = ResourceManager.GetObject("1435861155_edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1435861214_remove_sign {
            get {
                object obj = ResourceManager.GetObject("1435861214_remove-sign", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1435861214_remove_sign1 {
            get {
                object obj = ResourceManager.GetObject("1435861214_remove-sign1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1435861214_remove_sign2 {
            get {
                object obj = ResourceManager.GetObject("1435861214_remove-sign2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1435861250_plus_sign {
            get {
                object obj = ResourceManager.GetObject("1435861250_plus-sign", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1435861266_gears {
            get {
                object obj = ResourceManager.GetObject("1435861266_gears", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1436409850_info {
            get {
                object obj = ResourceManager.GetObject("1436409850_info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _150x150 {
            get {
                object obj = ResourceManager.GetObject("150x150", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2 {
            get {
                object obj = ResourceManager.GetObject("2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3 {
            get {
                object obj = ResourceManager.GetObject("3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _32 {
            get {
                object obj = ResourceManager.GetObject("32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bw_qa {
            get {
                object obj = ResourceManager.GetObject("bw-qa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Абаза
        ///Абакан
        ///Абан
        ///Абатский
        ///Абдулино
        ///Абинск
        ///Авангардное
        ///Агаповка
        ///Агинское
        ///Агрыз
        ///Адамовка
        ///Адлер
        ///Адреаполь
        ///Адыгейск
        ///Адыге-Хабль
        ///Азнакаево
        ///Азов
        ///Азово
        ///Айкино
        ///Акбулак
        ///Акбулак
        ///Аксай
        ///Аксарка
        ///Аксубаево
        ///Актаныш
        ///Акулово
        ///Акша
        ///Акъяр
        ///Алагир
        ///Алапаевск
        ///Алатырь
        ///Алдан
        ///Алеевка
        ///Алейск
        ///Александров
        ///Александров Гай
        ///Александровка
        ///Александровка
        ///Александровск
        ///Александровское
        ///Александровское
        ///Александро-Невский
        ///Алексеевка
        ///Алексеевка
        ///Алексеевка
        ///Алексеевская
        ///Алексеевское
        ///Алексин
        ///Аликово
        ///А [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string cities {
            get {
                return ResourceManager.GetString("cities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vubqepik@ddfqhegm.ru
        ///yxlddtn@wuanqclo.ru
        ///yvokbjti@boruaem.ru
        ///whjsqhc@rmkilb.ru
        ///bkfkxewo@upryebt.ru
        ///bcfefdho@divjyc.ru
        ///uqkus@jyrrxbo.ru
        ///dqsoh@upvhwv.ru
        ///bnrhum@dmqycms.ru
        ///lmfga@ardtrs.ru
        ///fudxw@hlajc.ru
        ///vypaslu@odibpvd.ru
        ///vomds@xrnafk.ru
        ///tlccrd@jrjive.ru
        ///blbhaxg@kwyujaw.ru
        ///sgkeur@yxsuq.ru
        ///fegov@glseleea.ru
        ///cwshm@qblyu.ru
        ///fbjhdo@frrfmd.ru
        ///aabxyqq@vbyme.ru
        ///ocuobnak@wiprun.ru
        ///qfdueq@madqf.ru
        ///ihpjm@owqkoqp.ru
        ///epjxvlm@sijtxc.ru
        ///owvtfa@rffeyla.ru
        ///oeoyvwqf@trxogarr.ru
        ///pcnswj@owdrqma.ru
        ///xtff [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string emails {
            get {
                return ResourceManager.GetString("emails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] manual {
            get {
                object obj = ResourceManager.GetObject("manual", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Александрович
        ///Алексеевич
        ///Анатольевич
        ///Андреевич
        ///Антонович
        ///Аркадьевич
        ///Артемович
        ///Бедросович
        ///Богданович
        ///Борисович
        ///Валентинович
        ///Валерьевич
        ///Васильевич
        ///Викторович
        ///Витальевич
        ///Владимирович
        ///Владиславович
        ///Вольфович
        ///Вячеславович
        ///Геннадиевич
        ///Георгиевич
        ///Григорьевич
        ///Данилович
        ///Денисович
        ///Дмитриевич
        ///Евгеньевич
        ///Егорович
        ///Ефимович
        ///Иванович
        ///Иваныч
        ///Игнатьевич
        ///Игоревич
        ///Ильич
        ///Иосифович
        ///Исаакович
        ///Кириллович
        ///Константинович
        ///Леонидович
        ///Львович 
        ///Максимович
        ///Матвеевич
        ///Михайлович
        ///Николаевич
        ///Олегов [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string middlenames {
            get {
                return ResourceManager.GetString("middlenames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ясон
        ///Ярослав
        ///Ярополк
        ///Яромир
        ///Януарий
        ///Ян
        ///Яков 
        ///Яким
        ///Язид
        ///Юхим
        ///Юрий
        ///Юлий
        ///Юлиан 
        ///Юджин
        ///Эрнест
        ///Эрик
        ///Эраст
        ///Эразм
        ///Эммануил 
        ///Эмиль 
        ///Эльдар 
        ///Эдуард
        ///Эдмунд
        ///Эдгар
        ///Эдвард
        ///Шамиль
        ///Шами
        ///Шакур
        ///Чеслав
        ///Цезарь
        ///Худаяр
        ///Христофор
        ///Христос
        ///Христиан 
        ///Харольд
        ///Харитон
        ///Харвей
        ///Хамид
        ///Халик
        ///Халид
        ///Хаким
        ///Фуад
        ///Фридрих
        ///Франц
        ///Фотий
        ///Фортунат
        ///Фома
        ///Флорентий 
        ///Флор 
        ///Фирс
        ///Филипп
        ///Филимон
        ///Филарет
        ///Фидель
        ///Фердинанд
        ///Ферапонт
        ///Феофил
        ///Феофан
        ///Феоктист
        ///Феодосий
        ///Фелициан
        ///Феликс
        ///Федот
        ///Федор 
        ///Фарх [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string names {
            get {
                return ResourceManager.GetString("names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +79357552372
        ///+79715220753
        ///+79085334001
        ///+79751446374
        ///+79827548630
        ///+79150546130
        ///+79401254051
        ///+79026883483
        ///+79533558484
        ///+79121330577
        ///+79256248661
        ///+79215505340
        ///+79573266082
        ///+79067521512
        ///+79637487716
        ///+79852488008
        ///+79307815550
        ///+79257407360
        ///+79118535813
        ///+79056852211
        ///+79361272745
        ///+79844312788
        ///+79875280150
        ///+79330417680
        ///+79772668806
        ///+79763306322
        ///+79406001140
        ///+79532552100
        ///+79511628338
        ///+79682318527
        ///+79266052735
        ///+79310110570
        ///+79166666235
        ///+79712203372
        ///+79245878281
        ///+79856263734
        ///+7915007 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string phones {
            get {
                return ResourceManager.GetString("phones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Яшин  
        ///Яснеев 
        ///Ясенев 
        ///Ярцев 
        ///Яромеев  
        ///Ярмольник 
        ///Янукович 
        ///Янковский 
        ///Янков  
        ///Янаев 
        ///Якушин 
        ///Якушев 
        ///Якунин  
        ///Якубович 
        ///Якубов 
        ///Яковлев 
        ///Якимов 
        ///Юферев  
        ///Юсупов 
        ///Юрьев  
        ///Юрнаев 
        ///Юнкин  
        ///Юдин 
        ///Юдашкин 
        ///Югов  
        ///Юганцев 
        ///Ювелев 
        ///Этуш  
        ///Эсце  
        ///Энтин  
        ///Эмануиль  
        ///Экель 
        ///Щукин  
        ///Щеткин 
        ///Щетинин 
        ///Щербина  
        ///Щербатых 
        ///Щербаков 
        ///Щепкин 
        ///Щекочихин  
        ///Щедров 
        ///Щедрин 
        ///Щеголихин 
        ///Щеголев  
        ///Щеглов 
        ///Щегельский 
        ///Щавельский 
        ///Шушалев 
        ///Шурша  
        ///Шурупов 
        ///Шульдешов 
        ///Шульгин 
        ///Шул [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string surnames {
            get {
                return ResourceManager.GetString("surnames", resourceCulture);
            }
        }
    }
}
